language: cpp
compiler: gcc
dist: trusty


env:
  - CODECOV_TOKEN="3aec67ed-b8ba-4418-b5c4-e63b2b86d6b5"

before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script: 
  - g++ -O3 -std=c++11 vbyte_compress.cpp growablearray.cpp tokeniser.cpp indexer.cpp -o indexer
  - ./indexer testfiles/test.xml
  - g++ -std=c++11 vbyte_compress.cpp search.cpp -lm -o search
  - ./search < testfiles/testsearch.txt > testfiles/testoutput.txt
  - diff testfiles/correctresult.txt testfiles/testoutput.txt
  - ./code_coverage.sh
  
  after_success:
  - bash <(curl -s https://codecov.io/bash)
